#!/bin/bash

fullPaths=()
curDir=$(pwd)
for i; do
    fullPaths+=("$curDir/$i")
done

export netDurationOp=$($HOME/.local/share/nemo/scripts/AVDurationC "${fullPaths[@]}" 2> /dev/null)
gnome-terminal -- sh -c "bash -c \"echo \\\$netDurationOp && read && exit\""